<?php
namespace App\Service;


class Upload
{
    private  $mailer;
    private $templating;

    public function __construct(\Swift_Mailer $mailer, \Twig_Environment $templating)
    {
        $this->mailer = $mailer;
        $this->templating = $templating;
    }

    public function Upload($file, $directory)
    {
        /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */

        if($file != null) {
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            $file->move(
                $directory,
                $fileName
            );

            return $fileName;
        }

        return null;
    }

    /**
     * @return string
     */
    protected function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}

