<?php
namespace App\Service;


use Symfony\Component\Filesystem\Filesystem;

class Upload
{
    public function __construct()
    {
    }

    public function Upload($file, $directory)
    {
        /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */

        if($file != null) {
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            $file->copy(
                $directory,
                $fileName
            );

            return $fileName;
        }

        return null;
    }

    public function FixtureUpload($path, $name)
    {
        $fileSystem = new Filesystem();
        $fileSystem->copy(
            str_replace('\\', '/', dirname(dirname(__DIR__)).'/public/images/figures/'.$name),
            str_replace('\\', '/', dirname(dirname(__DIR__)).'/public/uploads/medias/'.$name));

        return $name;
    }

    /**
     * @return string
     */
    protected function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}

