<?php
namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Entity\TrickMedia;
use App\Form\CommentType;
use App\Form\TrickMediaType;
use App\Form\TrickType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\File\File;

class TrickController extends AbstractController
{
    /**
     * @Route("/Tricks", name="app_tricks")
     */
    public function showfigureslist(EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);

        $tricks = $repository->findAll();

        return $this->render('trick/list.html.twig', ['tricks' => $tricks]);
    }

    /**
     * @Route("/Trick/{slug}", name="app_trick")
     */
    public function show($slug, Request $request, EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);
        $repositorycom = $em->getRepository(Comment::class);

        $trick = $repository->findOneBy(['name' => $slug]);
        $form = $this->createForm(CommentType::class);

        $comments = ($trick != null) ? $repositorycom->findBy(['trickid' => $trick->getId()], array('updatedate' => 'DESC'), $this->getParameter('comment_per_page'), 0) : '';

        if ($request->getMethod() == 'POST')
        {
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $user = $this->getUser();
                $com = $form->getData();
                $com->setTrickid($trick);
                $com->setAuthorid($user);
                $com->setUpdatedate(new \DateTime('@'.strtotime('now')));

                $em->persist($com);
                $em->flush();

                return $this->redirectToRoute('app_trick', array('slug' => $slug));
            }
        }

        return $this->render('trick/detail.html.twig', [
            'trick' => $trick,
            'commentform' => $form->createView(),
            'comments' => $comments,
            'commpentbaseindex' => $this->getParameter('comment_per_page'),
            'editmode' => false
        ]);
    }

    /**
     * @return string
     */
    protected function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/Trick/{slug}/addmedia", name="app_trick_addmedia")
     * @Security("has_role('ROLE_USER')")
     */
    public function addmedia($slug, Request $request, EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);
        $trick = $repository->findOneBy(['name' => $slug]);

        $trickmedia = new TrickMedia();
        $form = $this->createForm(TrickMediaType::class, $trickmedia);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $trickmedia->getLink();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('upload_directory'),
                $fileName
            );

            $trickmedia->setLink($fileName);
            $trickmedia->setIdFigure($trick);
            $trickmedia->setType(0);

            $em->persist($trickmedia);
            $em->flush();
            $this->addFlash('notice','Le nouveau média à été ajoutée');

            return $this->redirectToRoute('app_trick', ['slug' => $trick->getName()]);
        }

        return $this->render('trick/addmedia.html.twig', [
            'trick' => $trick,
            'mediaform' => $form->createView(),
            'editmode' => false]);
    }

    /**
     * @Route("/Trick/{slug}/edit", name="app_trick_edit")
     * @Security("has_role('ROLE_USER')")
     */
    public function edit($slug, Request $request, EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);

        $trick = $repository->findOneBy(['name' => $slug]);
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $trick->setUpdatedDate(new \DateTime('now'));
            $em->flush();
            $this->addFlash('notice','La figure à été éditée');

            return $this->redirectToRoute('app_trick', ['slug' => $form->getViewData()->getName()]);
        }

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'trickform' => $form->createView(),
            'editmode' => true]);
    }

    /**
     * @Route("/TrickNew", name="app_trick_new")
     * @Security("has_role('ROLE_USER')")
     */
    public function add(Request $request, EntityManagerInterface $em)
    {
        //TODO : Créer la figure à l'ouverture de la page mais la masquer tant que le formulaire n'est pas compléter on peut ainsi envoyer des images lié à la figure
        //TODO : Pour la photo de couverture prendre la première image quand existante

        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $trick->setPublishedAt(new \DateTime('now'));
            $trick->setUpdatedDate(new \DateTime('now'));
            $trick->setAuthorid($this->getUser());
            $trick->setCoverMedia(null);

            $em->persist($trick);
            $em->flush();
            $this->addFlash('notice','La figure à été ajoutée');

            return $this->redirectToRoute('app_trick', ['slug' => $form->getViewData()->getName()]);
        }

        return $this->render('trick/add.html.twig', [
            'trick' => $trick,
            'trickform' => $form->createView(),
            'editmode' => true]);
    }

    /**
     * @Route("/Trick/{slug}/trash", name="app_trick_trash")
     * @Security("has_role('ROLE_USER')")
     */
    public function trash($slug, Request $request, EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);

        $trick = $repository->findOneBy(['name' => $slug]);

        if($trick != null) {
            $em->remove($trick);
            $em->flush();
        }

        $this->addFlash('notice','La figure à été supprimées');

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/TrickCom/{slug}/{index}", name="app_commentajax")
     */
    public function ajaxcomment($slug, $index, EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);
        $repositorycom = $em->getRepository(Comment::class);

        $trick = $repository->findOneBy(['id' => $slug]);
        $comments = $repositorycom->findBy(['trickid' => $trick->getId()], array('updatedate' => 'DESC'), $this->getParameter('comment_per_page'), $index);

        $results = array();

        foreach($comments as $comment)
        {
            $results[] = array('id' => $comment->getId(), 'author' => $comment->getAuthorid()->getUsername(), 'content' => $comment->getContent(), 'date' => $comment->getUpdatedate()->format('d/m/Y h:i'));
        }

        return $this->json($results);
    }

    /**
     * @Route("/TrickLoad/{index}", name="app_figureajax")
     */
    public function ajaxfigure($index, EntityManagerInterface $em)
    {
        $repository = $em->getRepository(Trick::class);

        $tricks = $repository->createQueryBuilder('n')->setMaxResults(6)->setFirstResult($index)->getQuery()->getResult();

        $results = array();

        foreach($tricks as $trick)
        {
            $results[] = array('id' => $trick->getId(), 'name' => $trick->getName(),  'author' => $trick->getAuthorid()->getUsername(), 'date' => $trick->getPublishedAt()->format('d/m/Y h:i'));
        }

        return $this->json($results);
    }
}